(define (make-account balance password)
    (define pass-failed-attempts 1)
    (define pass-fail-threshold 7)
    (define (withdraw amount)
        (if (>= balance amount)
            (begin (set! balance (- balance amount)) balance)
           "Not enouth money"
        )
    )
    (define (deposit amount)
        (set! balance (+ balance amount))
        balance
    )
    (define (call-the-cops) "Whiy whiy whiy")
    (define (dispatch pass m)
        (cond
            ((> pass-failed-attempts pass-fail-threshold) call-the-cops)
            ((not (eq? pass password)) 
                (begin 
                    (set! pass-failed-attempts (+ pass-failed-attempts 1))
                    (lambda (arg) "Wrong password")
                )
            )
            ((eq? m 'withdraw) withdraw)
            ((eq? m 'deposit) deposit)
            (else (display "Unknown call"))
        )
    )
    dispatch
)

(define acc (make-account 100 'say-and-pass))
((acc 'say-and-pass1 'withdraw) 40)
((acc 'say-and-pass1 'withdraw) 40)
((acc 'say-and-pass1 'withdraw) 40)
((acc 'say-and-pass1 'withdraw) 40)
((acc 'say-and-pass1 'withdraw) 40)
((acc 'say-and-pass1 'withdraw) 40)
((acc 'say-and-pass1 'withdraw) 40)
;((acc 'say-and-pass1 'withdraw) 40)
