(define (stream-limit stream tolerance)
    (if (< (abs (- (stream-car stream) (stream-cdr stream))) tolerance)
        (stream-car stream)
        (stream-limit (stream-cdr stream) tolerance)
    )
)
